"""The library: room templates and workshop clusters.

The owner's design, and the reason this file exists rather than a floor-plan generator:

    использование именно шаблонов внутри игры внутри двхака
    ...
    отбор комнат уже вести вне обучения основного Агента

So designs are DATA, not behaviour. The agent asks for "bedroom, tier 3" or "woodworking,
size 2"; it never learns a layout. Improving the layouts is an offline search that writes
new entries here, outside the agent's training loop.

Everything below is decoded from DFHack's own blueprint library and its own key tables
(`hack/data/blueprints/`, `hack/scripts/internal/quickfort/{build,place}.lua`), not
written from memory. That distinction has already cost this project three invented enum
names, each of which failed silently.
"""

from __future__ import annotations

from dataclasses import dataclass, field


class LibraryError(ValueError):
    """A library entry is malformed — a programming error, not agent input."""


# quickfort's own key tables. Kept here so a cluster can be declared in the same
# vocabulary the blueprints use, and so a typo is a KeyError at import rather than a
# blueprint that silently builds the wrong thing.
WORKSHOP_KEYS = {
    "wc": "Carpenters",
    "wm": "Masons",
    "wr": "Craftsdwarfs",
    "wt": "Mechanics",
    "wl": "Still",
    "wk": "Clothiers",
    "wb": "Bowyers",
    "ws": "Siege",
}

STOCKPILE_KEYS = {
    "a": "animals", "f": "food", "u": "furniture", "n": "coins", "y": "corpses",
    "r": "refuse", "s": "stone", "w": "wood", "e": "gems", "b": "bars_blocks",
    "h": "cloth", "l": "leather", "z": "ammo", "g": "finished_goods",
    "p": "weapons", "d": "armor", "c": "custom",
}


@dataclass(frozen=True)
class Template:
    """One room design the agent can stamp.

    `footprint` is the blueprint's own extent, so a caller can ask whether it fits before
    trying — the same discipline as `build_farm_plot` refusing rather than building
    somewhere useless.
    """

    name: str
    path: str                       # relative to DFHack's blueprints directory
    modes: tuple[str, ...]          # #dig / #build / #place / #zone sections it contains
    footprint: tuple[int, int]      # width, height in tiles
    makes: str                      # what a player gets out of it
    start: str = ""                 # the blueprint's declared anchor
    shipped: bool = True            # ships with DFHack, versus generated by our search
    tier: int = 0                   # 0 = not aimed at a quality tier

    def __post_init__(self) -> None:
        if not self.modes:
            raise LibraryError(f"{self.name}: a template must declare its modes")
        w, h = self.footprint
        if w <= 0 or h <= 0:
            raise LibraryError(f"{self.name}: footprint {self.footprint} is not an area")


@dataclass(frozen=True)
class Cluster:
    """A group of workshops and the stockpiles that feed them.

    The four properties the owner asked the agent to choose on:

        среди чего должен агент выбирать — это их цена создания... и количество их
        возможностей, и... что можно восполнить, если их построить

    plus several SIZES per cluster. `cost` is in plain building materials because that is
    what the owner asked for — "можно просто в каких-то числах" — and because it is the
    number the fort actually pays.
    """

    name: str
    size: int                       # 1..4, several variants of the same cluster
    workshops: tuple[str, ...]      # quickfort keys, e.g. ("wc", "wm")
    stockpiles: tuple[str, ...]     # quickfort keys, e.g. ("w", "s")
    replenishes: tuple[str, ...]    # what the fort can make more of once it stands
    blueprint: str = ""             # a shipped blueprint, when one already does this
    capabilities: int = 0           # how many distinct jobs it unlocks; measured, not guessed

    def __post_init__(self) -> None:
        for key in self.workshops:
            if key not in WORKSHOP_KEYS:
                raise LibraryError(f"{self.name}: unknown workshop key {key!r}")
        for key in self.stockpiles:
            if key not in STOCKPILE_KEYS:
                raise LibraryError(f"{self.name}: unknown stockpile key {key!r}")
        if not 1 <= self.size <= 4:
            raise LibraryError(f"{self.name}: size {self.size} outside 1..4")

    @property
    def cost(self) -> int:
        """Build material the cluster costs, in items.

        One per workshop is DF's own rule for the basic shops in this library, and
        stockpiles cost nothing to place. Declared as a property rather than a stored
        number so it cannot drift from the workshop list.
        """
        return len(self.workshops)


# ---------------------------------------------------------------- shipped templates
# Headers and extents read off the files themselves; `modes` from the section markers
# each file actually contains.
TEMPLATES: tuple[Template, ...] = (
    Template(
        name="embark", path="embark.csv", modes=("build", "place"),
        footprint=(16, 17), start="8;2;center of wagon",
        makes="the four post-embark workshops and the seven stockpiles that feed them",
    ),
    Template(
        name="bedrooms28", path="bedrooms/28-3-Modified_Windmill_Villas.csv",
        modes=("dig",), footprint=(22, 74), start="12;12",
        makes="28 bedrooms, 3 tiles each",
    ),
    Template(
        name="bedrooms48", path="bedrooms/48-4-Raynard_Whirlpool_Housing.csv",
        modes=("dig",), footprint=(33, 209), start="17;17",
        makes="48 bedrooms, 4 tiles each",
    ),
    Template(
        name="bedrooms95", path="bedrooms/95-9-Hactar1_3_Branch_Tree.csv",
        modes=("dig",), footprint=(70, 228), start="36;73",
        makes="95 bedrooms including 14 suites, and 190 tombs",
    ),
    Template(
        name="tombs24", path="tombs/Mini_Saracen.csv", modes=("dig",),
        footprint=(12, 26), start="6;6", makes="a crypt for 24 corpses",
    ),
    Template(
        name="tombs513", path="tombs/The_Saracen_Crypts.csv", modes=("dig",),
        footprint=(48, 99), start="24;25", makes="a crypt for 513 corpses",
    ),
    Template(
        name="dreamfort", path="dreamfort.csv", modes=("notes",),
        footprint=(42, 3238), start="",
        makes="a complete self-sustaining fortress, in stages",
    ),
    Template(
        name="aquifer_tap", path="aquifer_tap.csv", modes=("notes",),
        footprint=(19, 73), start="", makes="a safe tap into an aquifer for water",
    ),
    Template(
        name="pump_stack", path="pump_stack.csv", modes=("notes",),
        footprint=(4, 80), start="", makes="a powered pump stack",
    ),
    Template(
        name="mineshafts", path="exploratory-mining/vertical-mineshafts.csv",
        modes=("dig",), footprint=(43, 42), start="",
        makes="exploratory mineshafts as stairs every third tile",
    ),
    Template(
        name="tunnels", path="exploratory-mining/tunnels.csv", modes=("dig",),
        footprint=(101, 52), start="", makes="exploratory tunnels every ten units",
    ),
)


# ---------------------------------------------------------------- clusters
# `embark` is decoded from DFHack's own file: wc/wt/wm/wr are the Carpenter's,
# Mechanic's, Mason's and Craftsdwarf's workshops, and it places wood, stone, finished
# goods, weapons, armor, food and furniture piles alongside them. That file IS the
# owner's cluster idea, already shipped, which is why the first entry quotes it rather
# than reinventing it.
CLUSTERS: tuple[Cluster, ...] = (
    Cluster(
        name="embark", size=2, blueprint="embark.csv",
        workshops=("wc", "wt", "wm", "wr"),
        stockpiles=("w", "s", "g", "p", "d", "f", "u"),
        replenishes=("furniture", "mechanisms", "blocks", "crafts"),
    ),
    Cluster(
        name="woodworking", size=1,
        workshops=("wc",), stockpiles=("w", "u"),
        replenishes=("beds", "tables", "chairs", "doors", "barrels", "bins"),
    ),
    Cluster(
        name="woodworking", size=2,
        workshops=("wc", "wc"), stockpiles=("w", "u"),
        replenishes=("beds", "tables", "chairs", "doors", "barrels", "bins"),
    ),
    Cluster(
        name="stoneworking", size=1,
        workshops=("wm",), stockpiles=("s", "u"),
        replenishes=("blocks", "stone furniture", "coffins"),
    ),
    Cluster(
        name="stoneworking", size=2,
        workshops=("wm", "wr"), stockpiles=("s", "u", "g"),
        replenishes=("blocks", "stone furniture", "coffins", "crafts"),
    ),
    Cluster(
        name="brewing", size=1,
        workshops=("wl",), stockpiles=("f",),
        replenishes=("drink",),
    ),
)

TEMPLATES_BY_NAME = {t.name: t for t in TEMPLATES}
CLUSTER_NAMES = tuple(dict.fromkeys(c.name for c in CLUSTERS))


def cluster(name: str, size: int = 1) -> Cluster | None:
    """The named cluster at the requested size, or the largest that is no bigger."""
    candidates = [c for c in CLUSTERS if c.name == name and c.size <= size]
    if not candidates:
        return None
    return max(candidates, key=lambda c: c.size)
